import { Album } from '../../models/album';

export const AlbumData : Album[] = 
[{
            album_type: "album",
            artists: [
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/4Uc8Dsxct0oMqx0P6i60ea"
                    },
                    href: "https://api.spotify.com/v1/artists/4Uc8Dsxct0oMqx0P6i60ea",
                    id: "4Uc8Dsxct0oMqx0P6i60ea",
                    name: "Conan Gray",
                    type: "artist",
                    uri: "spotify:artist:4Uc8Dsxct0oMqx0P6i60ea"
                }
            ],
            available_markets: [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            external_urls: {
                spotify: "https://open.spotify.com/album/2CMlkzFI2oDAy5MbyV7OV5"
            },
            href: "https://api.spotify.com/v1/albums/2CMlkzFI2oDAy5MbyV7OV5",
            id: "2CMlkzFI2oDAy5MbyV7OV5",
            images: [
                {
                    height: 640,
                    url: "https://i.scdn.co/image/ab67616d0000b27388e3cda6d29b2552d4d6bc43",
                    width: 640
                },
                {
                    height: 300,
                    url: "https://i.scdn.co/image/ab67616d00001e0288e3cda6d29b2552d4d6bc43",
                    width: 300
                },
                {
                    height: 64,
                    url: "https://i.scdn.co/image/ab67616d0000485188e3cda6d29b2552d4d6bc43",
                    width: 64
                }
            ],
            name: "Kid Krow",
            release_date: "2020-03-20",
            release_date_precision: "day",
            total_tracks: 12,
            type: "album",
            uri: "spotify:album:2CMlkzFI2oDAy5MbyV7OV5"
        },
        {
            album_type: "album",
            artists: [
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/0bzfPKdbXL5ezYW2z3UGQj"
                    },
                    href: "https://api.spotify.com/v1/artists/0bzfPKdbXL5ezYW2z3UGQj",
                    id: "0bzfPKdbXL5ezYW2z3UGQj",
                    name: "Michael Kiwanuka",
                    type: "artist",
                    uri: "spotify:artist:0bzfPKdbXL5ezYW2z3UGQj"
                }
            ],
            available_markets: [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            external_urls: {
                spotify: "https://open.spotify.com/album/1yIqauTni1V7l7djYAKSsZ"
            },
            href: "https://api.spotify.com/v1/albums/1yIqauTni1V7l7djYAKSsZ",
            id: "1yIqauTni1V7l7djYAKSsZ",
            images: [
                {
                    height: 640,
                    url: "https://i.scdn.co/image/ab67616d0000b27360ada139840fb439d6750f27",
                    width: 640
                },
                {
                    height: 300,
                    url: "https://i.scdn.co/image/ab67616d00001e0260ada139840fb439d6750f27",
                    width: 300
                },
                {
                    height: 64,
                    url: "https://i.scdn.co/image/ab67616d0000485160ada139840fb439d6750f27",
                    width: 64
                }
            ],
            name: "KIWANUKA",
            release_date: "2019-10-10",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:1yIqauTni1V7l7djYAKSsZ"
        }
    
]