import { Track } from './../../models/track';
export const trackData : Track[] = 
[
    {
        album: {
            album_type: "single",
            artists: [
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/6UCQYrcJ6wab6gnQ89OJFh"
                    },
                    href: "https://api.spotify.com/v1/artists/6UCQYrcJ6wab6gnQ89OJFh",
                    id: "6UCQYrcJ6wab6gnQ89OJFh",
                    name: "Headie One",
                    type: "artist",
                    uri: "spotify:artist:6UCQYrcJ6wab6gnQ89OJFh"
                },
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/4Xi6LSfFqv26XgP9NKN26U"
                    },
                    href: "https://api.spotify.com/v1/artists/4Xi6LSfFqv26XgP9NKN26U",
                    id: "4Xi6LSfFqv26XgP9NKN26U",
                    name: "AJ Tracey",
                    type: "artist",
                    uri: "spotify:artist:4Xi6LSfFqv26XgP9NKN26U"
                },
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/2SrSdSvpminqmStGELCSNd"
                    },
                    href: "https://api.spotify.com/v1/artists/2SrSdSvpminqmStGELCSNd",
                    id: "2SrSdSvpminqmStGELCSNd",
                    name: "Stormzy",
                    type: "artist",
                    uri: "spotify:artist:2SrSdSvpminqmStGELCSNd"
                }
            ],
            available_markets: [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            external_urls: {
                spotify: "https://open.spotify.com/album/4DlHEcnhhUJbLuRvaOfdxC"
            },
            href: "https://api.spotify.com/v1/albums/4DlHEcnhhUJbLuRvaOfdxC",
            id: "4DlHEcnhhUJbLuRvaOfdxC",
            images: [
                {
                    height: 640,
                    url: "https://i.scdn.co/image/ab67616d0000b273f737e4c0069e9406d7e2a665",
                    width: 640
                },
                {
                    height: 300,
                    url: "https://i.scdn.co/image/ab67616d00001e02f737e4c0069e9406d7e2a665",
                    width: 300
                },
                {
                    height: 64,
                    url: "https://i.scdn.co/image/ab67616d00004851f737e4c0069e9406d7e2a665",
                    width: 64
                }
            ],
            name: "Ain't It Different (feat. AJ Tracey & Stormzy)",
            release_date: "2020-08-20",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:4DlHEcnhhUJbLuRvaOfdxC"
        },
        artists: [
            {
                external_urls: {
                    spotify: "https://open.spotify.com/artist/6UCQYrcJ6wab6gnQ89OJFh"
                },
                href: "https://api.spotify.com/v1/artists/6UCQYrcJ6wab6gnQ89OJFh",
                id: "6UCQYrcJ6wab6gnQ89OJFh",
                name: "Headie One",
                type: "artist",
                uri: "spotify:artist:6UCQYrcJ6wab6gnQ89OJFh"
            },
            {
                external_urls: {
                    spotify: "https://open.spotify.com/artist/4Xi6LSfFqv26XgP9NKN26U"
                },
                href: "https://api.spotify.com/v1/artists/4Xi6LSfFqv26XgP9NKN26U",
                id: "4Xi6LSfFqv26XgP9NKN26U",
                name: "AJ Tracey",
                type: "artist",
                uri: "spotify:artist:4Xi6LSfFqv26XgP9NKN26U"
            },
            {
                external_urls: {
                    spotify: "https://open.spotify.com/artist/2SrSdSvpminqmStGELCSNd"
                },
                href: "https://api.spotify.com/v1/artists/2SrSdSvpminqmStGELCSNd",
                id: "2SrSdSvpminqmStGELCSNd",
                name: "Stormzy",
                type: "artist",
                uri: "spotify:artist:2SrSdSvpminqmStGELCSNd"
            }
        ],
        available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
        ],
        disc_number: 1,
        duration_ms: 196363,
        explicit: true,
        external_ids: {
            isrc: "GBARL2001008"
        },
        external_urls: {
            spotify: "https://open.spotify.com/track/6NJfIydBMYrXvlaXsFxmc8"
        },
        href: "https://api.spotify.com/v1/tracks/6NJfIydBMYrXvlaXsFxmc8",
        id: "6NJfIydBMYrXvlaXsFxmc8",
        is_local: false,
        name: "Ain't It Different (feat. AJ Tracey & Stormzy)",
        popularity: 83,
        preview_url: "https://p.scdn.co/mp3-preview/e539d31ef4045a842fb853012c377ece9237b174?cid=774b29d4f13844c495f206cafdad9c86",
        track_number: 1,
        type: "track",
        uri: "spotify:track:6NJfIydBMYrXvlaXsFxmc8",
        audio_feature: 
            {
              danceability: 0.767,
              energy: 0.569,
              key: 4,
              loudness: -6.805,
              mode: 0,
              speechiness: 0.216,
              acousticness: 0.00988,
              instrumentalness: 0.0000145,
              liveness: 0.109,
              valence: 0.524,
              tempo: 77.052,
              type: "audio_features",
              id: "6NJfIydBMYrXvlaXsFxmc8",
              uri: "spotify:track:6NJfIydBMYrXvlaXsFxmc8",
              track_href: "https://api.spotify.com/v1/tracks/6NJfIydBMYrXvlaXsFxmc8",
              analysis_url: "https://api.spotify.com/v1/audio-analysis/6NJfIydBMYrXvlaXsFxmc8",
              duration_ms: 196363,
              time_signature: 4
            }
          
        
    },
    {
        album: {
            album_type: "album",
            artists: [
                {
                    external_urls: {
                        spotify: "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
                    },
                    href: "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
                    id: "4MCBfE4596Uoi2O4DtmEMz",
                    name: "Juice WRLD",
                    type: "artist",
                    uri: "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
                }
            ],
            available_markets: [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            external_urls: {
                spotify: "https://open.spotify.com/album/6tkjU4Umpo79wwkgPMV3nZ"
            },
            href: "https://api.spotify.com/v1/albums/6tkjU4Umpo79wwkgPMV3nZ",
            id: "6tkjU4Umpo79wwkgPMV3nZ",
            images: [
                {
                    height: 640,
                    url: "https://i.scdn.co/image/ab67616d0000b273f7db43292a6a99b21b51d5b4",
                    width: 640
                },
                {
                    height: 300,
                    url: "https://i.scdn.co/image/ab67616d00001e02f7db43292a6a99b21b51d5b4",
                    width: 300
                },
                {
                    height: 64,
                    url: "https://i.scdn.co/image/ab67616d00004851f7db43292a6a99b21b51d5b4",
                    width: 64
                }
            ],
            name: "Goodbye & Good Riddance",
            release_date: "2018-12-10",
            release_date_precision: "day",
            total_tracks: 17,
            type: "album",
            uri: "spotify:album:6tkjU4Umpo79wwkgPMV3nZ"
        },
        artists: [
            {
                external_urls: {
                    spotify: "https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz"
                },
                href: "https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz",
                id: "4MCBfE4596Uoi2O4DtmEMz",
                name: "Juice WRLD",
                type: "artist",
                uri: "spotify:artist:4MCBfE4596Uoi2O4DtmEMz"
            }
        ],
        available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
        ],
        disc_number: 1,
        duration_ms: 165819,
        explicit: true,
        external_ids: {
            isrc: "USUG11800651"
        },
        external_urls: {
            spotify: "https://open.spotify.com/track/4VXIryQMWpIdGgYR4TrjT1"
        },
        href: "https://api.spotify.com/v1/tracks/4VXIryQMWpIdGgYR4TrjT1",
        id: "4VXIryQMWpIdGgYR4TrjT1",
        is_local: false,
        name: "All Girls Are The Same",
        popularity: 86,
        preview_url: null,
        track_number: 2,
        type: "track",
        uri: "spotify:track:4VXIryQMWpIdGgYR4TrjT1",
        audio_feature: {
            danceability: 0.671,
            energy: 0.529,
            key: 0,
            loudness: -7.226,
            mode: 1,
            speechiness: 0.307,
            acousticness: 0.0769,
            instrumentalness: 0.000335,
            liveness: 0.0856,
            valence: 0.203,
            tempo: 161.989,
            type: "audio_features",
            id: "4VXIryQMWpIdGgYR4TrjT1",
            uri: "spotify:track:4VXIryQMWpIdGgYR4TrjT1",
            track_href: "https://api.spotify.com/v1/tracks/4VXIryQMWpIdGgYR4TrjT1",
            analysis_url: "https://api.spotify.com/v1/audio-analysis/4VXIryQMWpIdGgYR4TrjT1",
            duration_ms: 165820,
            time_signature: 4
          }
    }
]